language: java

script:
  - mvn verify
  - mvn package -Popenshift
  - eval mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V  
  
jdk:
  - oraclejdk8
  
cache:
  directories:
  - $HOME/.m2